### ISSUE TITLE
Error while evaluating conditional: build_makefile and not acquia_cloud_connector

### ISSUE THREAD

**Issue by fiasco** [srowlands/govcms-devkit#29]
On OSX with Vagrant and Ansible. When running vagrant provision, I get the following error
![skitch 3](https://cloud.githubusercontent.com/assets/108160/10153492/64ffbd5e-66b9-11e5-9a2a-2b833219fc29.png)

While I can see that this issue is steming from [here](https://github.com/srowlands/govcms-devkit/blob/master/provisioning/tasks/build-makefile.yml#L2) I'm not really sure on how to progress past this point.

**Comment by stooit** [comment]
Thanks @fiasco, this was inadvertently introduced in PR #28, which optionally allows for syncing a govCMS site from Acquia Cloud during the provisioning process.

The example configuration files weren't updated to reflect the change, hence the failure. Fixed in [latest commit](https://github.com/srowlands/govcms-devkit/commit/d1e7f4b98817ceeed969a7c6c4fa8fb769bfa08f).
